// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjqQGeJDzok0ghWc6euisnX7SbAv-Z0JY',
    appId: '1:35298345559:web:225d558c62947e5e745912',
    messagingSenderId: '35298345559',
    projectId: 'mini-wallet-b4fce',
    authDomain: 'mini-wallet-b4fce.firebaseapp.com',
    storageBucket: 'mini-wallet-b4fce.firebasestorage.app',
    measurementId: 'G-3QC26LHBQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK0MT62O6oPN93YdhFn_g7m4iaPJK2xZ4',
    appId: '1:35298345559:android:25a3a13019e55711745912',
    messagingSenderId: '35298345559',
    projectId: 'mini-wallet-b4fce',
    storageBucket: 'mini-wallet-b4fce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy256WCJnO8Ky5YZ91-7qoQZzyWjijyzY',
    appId: '1:35298345559:ios:a6240cbc3de4190a745912',
    messagingSenderId: '35298345559',
    projectId: 'mini-wallet-b4fce',
    storageBucket: 'mini-wallet-b4fce.firebasestorage.app',
    iosBundleId: 'com.example.miniWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy256WCJnO8Ky5YZ91-7qoQZzyWjijyzY',
    appId: '1:35298345559:ios:a6240cbc3de4190a745912',
    messagingSenderId: '35298345559',
    projectId: 'mini-wallet-b4fce',
    storageBucket: 'mini-wallet-b4fce.firebasestorage.app',
    iosBundleId: 'com.example.miniWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjqQGeJDzok0ghWc6euisnX7SbAv-Z0JY',
    appId: '1:35298345559:web:8ab32d49092e79be745912',
    messagingSenderId: '35298345559',
    projectId: 'mini-wallet-b4fce',
    authDomain: 'mini-wallet-b4fce.firebaseapp.com',
    storageBucket: 'mini-wallet-b4fce.firebasestorage.app',
    measurementId: 'G-F4FCFTPGBW',
  );
}
